version: "3"
services:
  ag:
    image: postgres:11
    container_name: "postgres"
    environment:
      - POSTGRES_DB=agdb
      - POSTGRES_USER=ag
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
