const { ENVIRONMENT, PORT, JWT_SECRET, EXPIRESIN, DATABASE_URL } = process.env;

export const constants = {
  ENVIRONMENT: ENVIRONMENT,
  PORT: PORT,
  SECRET: JWT_SECRET,
  EXPIRESIN: EXPIRESIN,
  DATABASE_UR: DATABASE_URL,
};
